import type { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "speakeasy",
    title: "SpeakEasy",
    subtitle: "AI language-learning app",
    tags: ["AI", "MOBILE", "PRODUCT", "FULL-STACK"],
    year: "2026",
    description:
      "A personalized content feed that helps adult English learners practice through news, vocabulary, and voice-first AI discussion.",
    body: "SpeakEasy is a mobile app for adult English learners who need practice that fits into daily life. Instead of asking users to attend another class or follow a rigid lesson path, it turns the content they already read into a learning environment: scrollable articles, tap-to-define vocabulary, read-aloud support, saved words, and AI conversation practice built around each article.",
    details: [
      { label: "Role", value: "Product strategy, UX, mobile app build" },
      {
        label: "Stack",
        value: "Expo, React Native, Node.js, Supabase, OpenAI",
      },
      { label: "Validation", value: "16-user cohort + expert ESL feedback" },
      { label: "Codebase", value: "~12,300 lines across mobile and backend" },
    ],
    sections: [
      {
        title: "Problem",
        body: "We wanted to design for adult English learners who need more practice but often cannot fit formal ESL classes into everyday life. The barriers are very practical: finding the right class, making time for it, getting there, and keeping up with it consistently. SpeakEasy approaches that problem by bringing practice into something many people already do every day: reading and scrolling through content that actually interests them.",
      },
      {
        title: "Product Idea",
        body: "The app replaces a lesson-first model with a personalized, single-column feed. Users choose articles based on their interests, then learn inside that article through audio, vocabulary support, translation, saved words, and an AI discussion feature that helps them speak about what they just read.",
      },
      {
        title: "Design Decisions",
        body: "The feed stays intentionally simple: one article at a time, plain headlines, short summaries, and low cognitive load. The AI conversation flow is voice-first rather than chat-first, using a phone-call mental model, one question at a time, and gentler feedback to reduce pressure.",
      },
    ],
    thumbnail: {
      src: "/images/projects/speakeasy/thumbnail.png",
      alt: "SpeakEasy app screens",
      width: 3000,
      height: 3000,
    },
    thumbnailFit: "contain",
    thumbnailBg: "#646448",
    previewTilt: -6,
    href: "/work/speakeasy",
    githubUrl: "https://github.com/Shreyas-30/SpeakEasy",
    downloads: [
      {
        label: "App Store",
        href: "https://testflight.apple.com/join/SfXpeTmx",
        badge: {
          src: "/images/projects/speakeasy/appstoredownload.png",
          alt: "Download SpeakEasy on the App Store",
          width: 288,
          height: 96,
        },
        qr: {
          src: "/images/projects/speakeasy/AppStore_QR_download.png",
          alt: "SpeakEasy App Store TestFlight QR code",
          width: 500,
          height: 500,
        },
      },
      {
        label: "Play Store",
        href: "https://forms.gle/GRhUe5kta3ZAa4gq9",
        badge: {
          src: "/images/projects/speakeasy/playstoredownload.png",
          alt: "Get SpeakEasy on Google Play",
          width: 288,
          height: 96,
        },
        qr: {
          src: "/images/projects/speakeasy/Form_QR_Andriod.png",
          alt: "SpeakEasy Android access form QR code",
          width: 500,
          height: 500,
        },
      },
    ],
    systemDesign: {
      src: "/images/projects/speakeasy/systemdesign.jpg",
      alt: "SpeakEasy system design diagram",
      width: 5222,
      height: 3000,
    },
    videos: [
      {
        src: "/images/projects/speakeasy/onboarding.mov",
        title: "Onboarding",
        caption:
          "Users start by picking the topics they care about: news, sports, technology, culture, and more. SpeakEasy uses those choices to build a personalised article feed from day one, so the very first thing you see feels relevant to you. No generic lesson plan, no cold start. Just content you'd actually want to read.",
      },
      {
        src: "/images/projects/speakeasy/article.mov",
        title: "Article learning",
        caption:
          "Each article becomes a self-contained learning unit. Tap any word to get an instant definition, listen to the full piece read aloud, save vocabulary to your personal word list, and pull up translations on demand. The learning is woven into the reading habit rather than sitting separate from it, lowering the barrier to practice every day.",
      },
      {
        src: "/images/projects/speakeasy/discuss.mov",
        title: "AI discussion",
        caption:
          "After reading, users can open a voice-first conversation with an AI tutor about the article they just finished. The AI asks one question at a time, phone-call style rather than chat style, giving space to think and respond naturally. Feedback is gentle and specific, designed to reduce the anxiety of speaking a second language out loud.",
      },
    ],
  },
  {
    slug: "kiro",
    title: "Kiro",
    subtitle: "AI money coach",
    tags: ["PRODUCT", "FINANCE", "AI", "FULL-STACK"],
    year: "SUMMER 2025",
    description:
      "Designed and built an AI money coach with Plaid-powered real-time insights. Shipped onboarding, coaching flows, and analytics. Now live with 1,000+ users.",
    body: "Kiro is your AI money coach, built to help you stop overthinking your finances and start taking action. It doesn't just explain your numbers; it tells you what to do next. I designed, built, and shipped the core onboarding and coaching experiences, and integrated Plaid APIs for real-time financial data. Now live at joinkiro.com with 1,000+ users.",
    thumbnail: {
      src: "/images/projects/kiro/kiro.png",
      alt: "Kiro — AI money coach",
      width: 1280,
      height: 719,
    },
    previewTilt: 5,
    href: "https://www.joinkiro.com/",
    external: true,
  },
  {
    slug: "smriti",
    title: "Smriti",
    subtitle: "Voice-first family storytelling platform",
    tags: ["PRODUCT", "AI", "STARTUP", "WEB"],
    year: "2026",
    description:
      "A multilingual storytelling platform that helps families capture oral histories across generations, languages, and distance.",
    body: "Smriti is a guided, voice-first storytelling platform for families whose histories live mostly in conversations, voice notes, and half-remembered anecdotes. It helps adult children, parents, and grandparents collect memories through culturally grounded prompts, native-language voice recordings, AI-assisted transcription and translation, and digital or physical keepsakes that make those stories easier to revisit and share.",
    details: [
      { label: "Role", value: "Co-founder, product strategy, UX, build" },
      {
        label: "Focus",
        value: "Voice-first story capture for Indian and diaspora families",
      },
      {
        label: "Research",
        value: "60+ survey respondents and user interviews",
      },
      {
        label: "Output",
        value: "Live web platform, digital archive, physical memory book concept",
      },
    ],
    sections: [
      {
        title: "Problem",
        body: "In many Indian and diaspora families, history is oral, scattered, and rarely documented beyond one generation. Families want to preserve those memories, but the work is hard to start and even harder to keep up with. Traditional memoir and ghostwriting models are too expensive, too manual, and often not designed for Hindi, Marathi, Tamil, or other regional-language storytelling.",
      },
      {
        title: "Product Idea",
        body: "Smriti turns memory preservation into a guided flow instead of a blank-page writing project. Families choose prompts, share them through familiar channels, capture responses in the storyteller's own voice and language, then use AI-assisted transcription, translation, and narrative editing to shape those recordings into a digital archive or printed keepsake.",
      },
      {
        title: "Audience",
        body: "The buyer is often an adult child living away from home, looking for a meaningful gift or a way to preserve family history before it disappears. The storyteller is usually a parent or grandparent who may be more comfortable speaking than writing, and who needs the process to feel natural, low-friction, and emotionally respectful.",
      },
      {
        title: "System Direction",
        body: "The product is built around a voice-to-publishing workflow: multilingual voice ingestion, preprocessing, AI orchestration, human review where needed, and publishable artifacts such as shareable stories, family archives, and physical books. The goal is not just to record audio, but to turn lived memory into something families can keep, revisit, and pass on.",
      },
    ],
    thumbnail: {
      src: "/images/projects/smriti/thumbnail-smriti.png",
      alt: "Smriti pitch deck cover and product screen",
      width: 7680,
      height: 4320,
    },
    previewTilt: -4,
    href: "/work/smriti",
    liveUrl: "https://smritistories.com",
    images: [
      {
        src: "/images/projects/smriti/product.jpg",
        alt: "Smriti product overview slide",
        width: 3200,
        height: 1800,
      },
      {
        src: "/images/projects/smriti/process-1.jpg",
        alt: "Smriti six-step story collection process",
        width: 3200,
        height: 1800,
      },
      {
        src: "/images/projects/smriti/architecture.jpg",
        alt: "Smriti voice-to-publishing workflow",
        width: 3200,
        height: 1800,
      },
    ],
  },
  {
    slug: "mechanical-cuckoo-clock",
    title: "Mechanical Cuckoo Clock",
    subtitle: "All-mechanical timepiece",
    tags: ["MECHANICAL", "CAD", "MACHINING", "FABRICATION", "CMF"],
    year: "FALL 2025",
    description:
      "A fully mechanical clock built with laser-cut gears, a CNC-routed wooden base, and a handmade kalimba for sound.",
    body: "A mechanical cuckoo clock built from scratch, powered entirely by falling weights. We laser-cut the gears, CNC-routed the wooden base, 3D printed face and built the rest from brass, sheet metal, aluminum tubing, wood, and acrylic. The sound comes from a handmade kalimba, so the whole thing works without microcontrollers or servos — just weight, movement, and a lot of careful tuning.",
    thumbnail: {
      src: "/images/projects/clock/thumbnail.jpg",
      alt: "Mechanical cuckoo clock",
      width: 2564,
      height: 2631,
    },
    previewTilt: -9,
    href: "/work/mechanical-cuckoo-clock",
    images: [
      {
        src: "/images/projects/clock/0.jpg",
        alt: "Mechanical cuckoo clock hero image",
        width: 3411,
        height: 5116,
      },
      {
        src: "/images/projects/clock/1.jpg",
        alt: "Clock assembly",
        width: 1280,
        height: 1672,
      },
      {
        src: "/images/projects/clock/2.jpg",
        alt: "Clock front view",
        width: 1280,
        height: 803,
      },
      {
        src: "/images/projects/clock/3.jpg",
        alt: "Gear train detail",
        width: 1280,
        height: 1002,
      },
      {
        src: "/images/projects/clock/4.jpg",
        alt: "Escapement mechanism",
        width: 1256,
        height: 2048,
      },
      {
        src: "/images/projects/clock/5.jpg",
        alt: "Pendulum and weights",
        width: 1280,
        height: 1690,
      },
      {
        src: "/images/projects/clock/6.jpg",
        alt: "Side profile",
        width: 1280,
        height: 812,
      },
      {
        src: "/images/projects/clock/7.jpg",
        alt: "Wood case detail",
        width: 1280,
        height: 1173,
      },
      {
        src: "/images/projects/clock/8.jpg",
        alt: "Clock face close-up",
        width: 1280,
        height: 1672,
      },
      {
        src: "/images/projects/clock/9.png",
        alt: "Mechanism overview",
        width: 1280,
        height: 1027,
      },
      {
        src: "/images/projects/clock/10.png",
        alt: "Gear cutting process",
        width: 1202,
        height: 2032,
      },
      {
        src: "/images/projects/clock/11.png",
        alt: "Finished clock",
        width: 1280,
        height: 850,
      },
    ],
  },
  {
    slug: "space-chess",
    title: "Space Chess",
    subtitle: "Machined chess set",
    tags: ["MECHANICAL", "MACHINING", "FABRICATION", "CMF"],
    year: "FALL 2025",
    description:
      "Walnut, aluminium, brass, acrylic. CNC lathe, CNC router, laser cutting, anodization. Built with three teammates over a semester.",
    body: "Space Chess is a material-driven chess set that reimagines a familiar game as something tactile, sculptural, and slightly otherworldly. We combined CNC-turned aluminum and brass pieces with a routed walnut board, laser-cut acrylic, sheet metal details, and anodized finishes.",
    details: [
      { label: "Course", value: "IPD 5010" },
      {
        label: "Machines",
        value: "Haas TL-1 lathe · CNC router · Laser cutter",
      },
      { label: "Materials", value: "Walnut · Aluminium · Brass · Acrylic" },
      {
        label: "Finishing",
        value: "Polishing · Anodization · Wood stain & coating",
      },
    ],
    sections: [
      {
        title: "The pieces",
        body: "Each piece is a three-part assembly: a common aluminium base, a turned body, and a top that changes per piece type. We turned everything on the Haas TL-1. The brass bottoms give them real weight when you pick them up. For the light set we laser-cut white acrylic crowns; the dark set went through anodization which gave them this really satisfying uniform black. Getting the threading right took a few iterations, we had to add height and adjust diameters before the tap and die would work reliably.",
      },
      {
        title: "The board",
        body: 'We glued up walnut stock, planed it flat, then ran it through the Tangen CNC router to cut the square grid and border geometry. The routing alone took about 12 hours with a ⅛" ball nose end mill. The edges where the aluminium sheets sit had to be hand-chiselled to get a clean fit. Finished it all with stain and a coat of sealant.',
      },
      {
        title: "What I learned",
        body: "CAM for a router is a different beast from lathe work. We had to split the roughing into sections to avoid stressing thin areas, and I learned the hard way that engraving depth needs to account for how much material you lose when deburring. Overall though, getting to work across that many processes in one project was exactly the kind of hands-on learning I came to Penn for.",
      },
    ],
    thumbnail: {
      src: "/images/projects/spacechess/thumbnail.JPG",
      alt: "Space Chess — machined chess set",
      width: 7008,
      height: 4672,
    },
    previewTilt: -3,
    href: "/work/space-chess",
    images: [
      {
        src: "/images/projects/spacechess/0.png",
        alt: "Space Chess — slide 1",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/spacechess/1.png",
        alt: "Space Chess — slide 2",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/spacechess/2.png",
        alt: "Space Chess — slide 3",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/spacechess/3.png",
        alt: "Space Chess — slide 4",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/spacechess/4.png",
        alt: "Space Chess — slide 5",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/spacechess/5.png",
        alt: "Space Chess — slide 6",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/spacechess/6.png",
        alt: "Space Chess — slide 7",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/spacechess/7.png",
        alt: "Space Chess — slide 8",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/spacechess/8.png",
        alt: "Space Chess — slide 9",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/spacechess/9.png",
        alt: "Space Chess — slide 10",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/spacechess/10.png",
        alt: "Space Chess — slide 11",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/spacechess/11.png",
        alt: "Space Chess — slide 12",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/spacechess/12.png",
        alt: "Space Chess — slide 13",
        width: 960,
        height: 540,
      },
    ],
  },
  {
    slug: "birdie",
    title: "Birdie",
    subtitle: "Machined multitool",
    tags: ["MECHANICAL", "MACHINING", "CAD"],
    year: "FALL 2025",
    description:
      "A CNC-machined multitool with a 50mm ruler, bottle opener, and hex keys. Built on a Haas Mini Mill.",
    body: "Birdie is a compact multitool machined from aluminium stock on a Haas Mini Mill. Three functions packed into one part: a 50mm ruler, a crown cap bottle opener, and hex key fits for M6, M5, and M4 fasteners. The project covered the full workflow from CAD design and GD&T tolerancing through CAM toolpath setup and hands-on machining, with careful attention to datum selection, feature tolerances, clamp placement, and surface finishing.",
    details: [
      { label: "Course", value: "IPD 5010" },
      { label: "Machine", value: "Haas Mini Mill" },
      {
        label: "Functions",
        value: "50mm ruler · bottle opener · M6/M5/M4 hex keys",
      },
      { label: "Material", value: "Aluminium stock" },
    ],
    sections: [
      {
        title: "Design & Tolerancing",
        body: "The central hexagonal cutout was chosen as Datum A. Key locating features were assigned profile tolerances of 0.005 relative to that datum, surface straightness was called out on the ruler edge, and the hex key holes were dimensioned directly from bit sizes to ensure a tight, functional fit.",
      },
      {
        title: "Machining Challenges",
        body: "The main challenges were sizing holes precisely to bit dimensions, managing how bit rest plane height affects total machining time, planning clamp placement to keep the stock properly aligned during each operation, and accounting for material removal during deburring when setting engraving depth.",
      },
    ],
    thumbnail: {
      src: "/images/projects/birdie/thumbmail.JPG",
      alt: "Birdie multitool — machined aluminium",
      width: 6000,
      height: 4000,
    },
    previewTilt: 4,
    href: "/work/birdie",
    images: [
      {
        src: "/images/projects/birdie/1.png",
        alt: "Birdie — slide 1",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/birdie/2.png",
        alt: "Birdie — slide 2",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/birdie/3.png",
        alt: "Birdie — slide 3",
        width: 960,
        height: 540,
      },
      {
        src: "/images/projects/birdie/4.png",
        alt: "Birdie — slide 4",
        width: 960,
        height: 540,
      },
    ],
  },
  {
    slug: "amtrak",
    title: "Amtrak Rebooked",
    subtitle: "Rail booking redesign",
    tags: ["UX", "RESEARCH", "SERVICE DESIGN", "PRODUCT"],
    year: "SPRING 2025",
    description: "Redesigning the Amtrak experience for first-time travellers.",
    body: "A redesign of the Amtrak experience focused on first-time train travellers. The project explored how Amtrak could reduce that initial friction, from finding the right route to understanding what to expect onboard, making the first trip feel approachable enough to become a habit.",
    thumbnail: {
      src: "/images/projects/amtrak/amtrak_thumbmail.png",
      alt: "Amtrak Rebooked",
      width: 1000,
      height: 1000,
    },
    previewTilt: 7,
    href: "/work/amtrak",
    images: [
      {
        src: "/images/projects/amtrak/1.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/2.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/3.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/4.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/5.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/6.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/7.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/8.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/9.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/10.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/11.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/12.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/13.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/14.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/15.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/16.png",
        alt: "Amtrak redesign",
        width: 2880,
        height: 1620,
      },
      {
        src: "/images/projects/amtrak/17.png",
        alt: "Amtrak redesign",
        width: 2880,
        height: 1620,
      },
      {
        src: "/images/projects/amtrak/18.png",
        alt: "Amtrak redesign",
        width: 2880,
        height: 1620,
      },
      {
        src: "/images/projects/amtrak/19.png",
        alt: "Amtrak redesign",
        width: 2880,
        height: 1620,
      },
      {
        src: "/images/projects/amtrak/20.png",
        alt: "Amtrak redesign",
        width: 2880,
        height: 1620,
      },
      {
        src: "/images/projects/amtrak/21.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/22.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/23.png",
        alt: "Amtrak redesign",
        width: 2892,
        height: 1632,
      },
      {
        src: "/images/projects/amtrak/24.png",
        alt: "Amtrak redesign",
        width: 2880,
        height: 1620,
      },
      {
        src: "/images/projects/amtrak/25.png",
        alt: "Amtrak redesign",
        width: 2880,
        height: 1620,
      },
      {
        src: "/images/projects/amtrak/26.png",
        alt: "Amtrak redesign",
        width: 2880,
        height: 1620,
      },
    ],
  },
  {
    slug: "autonomous-battlebot",
    title: "Autonomous Battlebot",
    subtitle: "Mechatronics project",
    tags: ["ROBOTICS", "EMBEDDED", "FABRICATION"],
    year: "SPRING 2025",
    description:
      "An autonomous mini battlebot built around ESP32 control, ToF sensing, and rapid-fabricated mechanical parts.",
    body: "Autonomous Battlebot is a small robotics platform built to sense, decide, and move without direct driver control. The bot uses an ESP32 microcontroller as the control layer, I2C communication for sensor integration, and time-of-flight sensors to detect nearby objects and react in real time. The chassis and mechanisms combined 3D-printed parts with laser-cut structural pieces, making it a compact exercise in embedded control, sensing, mechanical packaging, and fast physical iteration.",
    details: [
      { label: "Controller", value: "ESP32" },
      { label: "Sensors", value: "I2C time-of-flight distance sensors" },
      { label: "Fabrication", value: "3D printing · Laser cutting" },
      {
        label: "Focus",
        value: "Mechatronics, autonomous sensing, control, and motion",
      },
    ],
    thumbnail: {
      src: "/images/projects/mechatronics/mechatronics_thumbnail.jpg",
      alt: "Autonomous Battlebot robot",
      width: 1280,
      height: 1078,
    },
    previewTilt: 6,
    href: "/work/autonomous-battlebot",
    youtubeId: "WQ-gsW8HgsE",
  },
  {
    slug: "timewise",
    title: "TimeWise",
    subtitle: "Student time-management app",
    tags: ["UX", "PRODUCT", "MOBILE"],
    year: "SPRING 2025",
    description:
      "A student-centered time management app that breaks assignments into doable tasks, adapts reminders, and makes progress easier to trust.",
    body: "TimeWise is a mobile productivity concept built around a simple promise: stop guessing, start doing. Designed for students who procrastinate because assignments feel vague or overwhelming, it translates coursework into smaller time estimates, visual progress, and focused work sessions.",
    details: [
      { label: "Context", value: "IPD 552 Problem Framing" },
      { label: "Role", value: "Research, product strategy, UX/UI design" },
      {
        label: "Focus",
        value: "Procrastination, planning confidence, student stress",
      },
      {
        label: "Output",
        value: "Mobile app concept, prototype flows, validation artifacts",
      },
    ],
    sections: [
      {
        title: "Problem",
        body: "Students often know what is due, but not how long the work will actually take. That uncertainty makes assignments feel larger than they are, which feeds procrastination and stress.",
      },
      {
        title: "Product Idea",
        body: "TimeWise reframes planning as an estimation-and-action loop. Students enter assignments, break them into smaller pieces, compare time expectations, and use a focused timer to move from planning into doing.",
      },
      {
        title: "Design Direction",
        body: "The interface stays intentionally calm: soft color, clear course progress, lightweight controls, and reward-style feedback. The goal is to make time visible without making the app feel like another assignment.",
      },
    ],
    thumbnail: {
      src: "/images/projects/timewise/TimeWise.png",
      alt: "TimeWise app screens and logo",
      width: 5557,
      height: 4320,
    },
    previewTilt: -7,
    href: "/work/timewise",
    gifs: [
      {
        src: "/images/projects/timewise/Gifs/1_details.gif",
        alt: "TimeWise assignment details flow",
        title: "Assignment details",
        caption:
          "Add course context, assignment scope, due date, and task breakdowns.",
      },
      {
        src: "/images/projects/timewise/Gifs/2_sort.gif",
        alt: "TimeWise sorting flow",
        title: "Prioritize work",
        caption: "Sort and compare coursework so the next task feels clear.",
      },
      {
        src: "/images/projects/timewise/Gifs/3_timer.gif",
        alt: "TimeWise focus timer flow",
        title: "Focus timer",
        caption:
          "Move from planning into a timed work session with pause and finish states.",
      },
    ],
    images: [
      {
        src: "/images/projects/timewise/Context.png",
        alt: "TimeWise project context",
        width: 7680,
        height: 4320,
      },
      {
        src: "/images/projects/timewise/Research.png",
        alt: "TimeWise research process",
        width: 7680,
        height: 4320,
      },
      {
        src: "/images/projects/timewise/Insight 1.png",
        alt: "TimeWise research insight 1",
        width: 7680,
        height: 4320,
      },
      {
        src: "/images/projects/timewise/Insight 2.png",
        alt: "TimeWise research insight 2",
        width: 7680,
        height: 4320,
      },
      {
        src: "/images/projects/timewise/Insight 3.png",
        alt: "TimeWise research insight 3",
        width: 7680,
        height: 4320,
      },
      {
        src: "/images/projects/timewise/HMW_.png",
        alt: "TimeWise how might we framing",
        width: 7680,
        height: 4320,
      },
      {
        src: "/images/projects/timewise/Design Opportunity.png",
        alt: "TimeWise design opportunity",
        width: 7680,
        height: 4320,
      },
      {
        src: "/images/projects/timewise/Concept.png",
        alt: "TimeWise concept",
        width: 7680,
        height: 4320,
      },
      {
        src: "/images/projects/timewise/Differentiation.png",
        alt: "TimeWise differentiation",
        width: 7680,
        height: 4320,
      },
      {
        src: "/images/projects/timewise/Home-1.png",
        alt: "TimeWise home screen",
        width: 7680,
        height: 4320,
      },
      {
        src: "/images/projects/timewise/AI Calculator.png",
        alt: "TimeWise assignment calculator",
        width: 7680,
        height: 4320,
      },
      {
        src: "/images/projects/timewise/Timer.png",
        alt: "TimeWise timer screen",
        width: 7680,
        height: 4320,
      },
      {
        src: "/images/projects/timewise/Awards.png",
        alt: "TimeWise awards screen",
        width: 7680,
        height: 4320,
      },
      {
        src: "/images/projects/timewise/Feedback-1.png",
        alt: "TimeWise feedback 1",
        width: 7680,
        height: 4320,
      },
      {
        src: "/images/projects/timewise/Feedback-2.png",
        alt: "TimeWise feedback 2",
        width: 7680,
        height: 4320,
      },
    ],
  },
  {
    slug: "laptop-stand",
    title: "Laptop Stand",
    subtitle: "Woodworking & industrial design",
    tags: ["ID", "CMF", "FABRICATION"],
    year: "FALL 2024",
    description: "CNC-cut wood, hand-assembled and stained. A study in CMF.",
    body: "A laptop stand designed in CAD and fabricated on a CNC router, from a digital model to a finished wooden object. The process covered joinery design, CNC toolpath setup, glueing the cut pieces, and finishing the surface with a wood stain.",
    thumbnail: {
      src: "/images/projects/laptopstand/1.png",
      alt: "Laptop stand",
      width: 1350,
      height: 1068,
    },
    previewTilt: -5,
    href: "/work/laptop-stand",
    youtubeId: "olIoftgoWJA",
    images: [
      {
        src: "/images/projects/laptopstand/1.png",
        alt: "CAD model and render",
        width: 1350,
        height: 1068,
      },
      {
        src: "/images/projects/laptopstand/2.png",
        alt: "Setting up the CNC router",
        width: 2600,
        height: 1446,
      },
      {
        src: "/images/projects/laptopstand/3.png",
        alt: "Cutting the wood on the CNC router",
        width: 2576,
        height: 1340,
      },
      {
        src: "/images/projects/laptopstand/4.png",
        alt: "Glueing the pieces together",
        width: 2538,
        height: 1378,
      },
      {
        src: "/images/projects/laptopstand/5.png",
        alt: "Finishing the surface with wood stain",
        width: 2370,
        height: 1312,
      },
      {
        src: "/images/projects/laptopstand/6.png",
        alt: "Finished laptop stand",
        width: 2658,
        height: 1496,
      },
    ],
  },
];
